// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BookList: typeof import('./src/components/BookList.vue')['default']
    Move: typeof import('./src/components/Move.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searcg: typeof import('./src/components/Searcg.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFieled: typeof import('vant/es')['Fieled']
    VanFiled: typeof import('vant/es')['Filed']
    VanForm: typeof import('vant/es')['Form']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPopupan: typeof import('vant/es')['Popupan']
    VanPopupanPopup: typeof import('vant/es')['PopupanPopup']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VantFiled: typeof import('vant/es')['tFiled']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
